
[[]]
description = "Enable pointer-authenticaton-codes and tagging (arm64e) features for non-platform binaries"
name = "-arm64e_preview_abi"
[[]]
name = "-bsdmgroot"
[[]]
name = "-corpse_threshold_system_limit"
[[]]
name = "-cpuid"
[[]]
description = "Disable user mode address space layout randomization"
name = "-disable_aslr"
[[]]
name = "-disable_atm"
[[]]
name = "-disable_cseg_write_protection"
[[]]
name = "-disable_freezer_cseg_acct"
[[]]
name = "-disable_mtx_chk"
[[]]
name = "-disable_procref_tracking"
[[]]
name = "-disable_syscallfilter"
[[]]
description = "Disable Haswell x86_64 optimization / instructions"
name = "-disable_x86_64h"
[[]]
name = "-enable_kprintf_spam"
[[]]
description = "Enable Haswell x86_64 optimization / instructions"
name = "-enable_x86_64h"
[[]]
name = "-fp_exceptions"
[[]]
name = "-gzalloc_mode"
[[]]
name = "-gzalloc_no_dfree_check"
[[]]
name = "-gzalloc_noconsistency"
[[]]
name = "-gzalloc_uf_mode"
[[]]
name = "-gzalloc_wp"
[[]]
name = "-interrupt_latency_assert_enable"
[[]]
name = "-kernel_text_ps_4K"
[[]]
name = "-kill_on_no_paging_space"
[[]]
name = "-l"
[[]]
name = "-minimalboot"
[[]]
name = "-multiq-deep-drain"
[[]]
name = "-multiq-sanity-check"
[[]]
name = "-no-copyio-zalloc-check"
[[]]
name = "-no-zp"
[[]]
name = "-no_corpses"
[[]]
name = "-no_shared_cr3"
[[]]
name = "-no_sigsys"
[[]]
name = "-no_slto_panic"
[[]]
name = "-no_vnode_drain"
[[]]
name = "-no_vnode_jetsam"
[[]]
name = "-nobsdmgroot"
[[]]
name = "-nogzalloc_mode"
[[]]
name = "-nokcmismatchpanic"
[[]]
name = "-nomsr35h"
[[]]
name = "-nomt_core"
[[]]
name = "-noprogress"
[[]]
name = "-novfscache"
[[]]
name = "-panic_on_exception_triage"
[[]]
name = "-pmap_disable_kheap_nx"
[[]]
name = "-pmap_disable_kstack_nx"
[[]]
name = "-pmap_pagetable_corruption_deassert"
[[]]
name = "-pmap_pcid_disable"
[[]]
name = "-pmap_smap_disable"
[[]]
name = "-pmap_smep_disable"
[[]]
name = "-pmap_trace"
[[]]
name = "-progress"
[[]]
name = "-qos-policy-allow"
[[]]
name = "-restore"
[[]]
name = "-rootdmg-ramdisk"
[[]]
name = "-rwroot_hack"
[[]]
name = "-s"
[[]]
name = "-show_pointers"
[[]]
name = "-topo"
[[]]
name = "-unsafe_kernel_text"
[[]]
description = "Boot the system into verbose mode"
name = "-v"
[[]]
name = "-vm_compressor_hybrid"
[[]]
name = "-vm_compressor_wk"
[[]]
name = "-vnode_cache_defeat"
[[]]
name = "-x"
[[]]
name = "-zc"
[[]]
name = "-zl"
[[]]
name = "-zleakoff"
[[]]
name = "-zleakon"
[[]]
name = "-zp"
[[]]
name = "-zt"
[[]]
name = "IgnoreFBTBlacklist"
[[]]
name = "TSC_deadline_timer"
[[]]
name = "TSC_sync_margin"
[[]]
name = "_fpu"
[[]]
name = "_panicd_corename"
[[]]
name = "_panicd_ip"
[[]]
name = "_router_ip"
[[]]
name = "alt-dyld"
[[]]
name = "alternate_debugger_init"
[[]]
name = "alternate_debugger_init_pages"
[[]]
name = "alternate_debugger_pause_for_load_at_boot"
[[]]
name = "aotlinger"
[[]]
name = "arm64_maxoffset"
[[]]
name = "arm_maxoffset"
[[]]
name = "arp0"
[[]]
name = "assertions"
[[]]
name = "atm_diagnostic_config"
[[]]
name = "avx512"
[[]]
name = "bad_static_mfree"
[[]]
name = "bg_preempt"
[[]]
name = "boot-uuid"
[[]]
name = "bootprofile_buffer_size"
[[]]
name = "bootprofile_interval_ms"
[[]]
name = "bootprofile_proc_name"
[[]]
name = "bootprofile_stackshot_flags"
[[]]
name = "bootprofile_type"
[[]]
name = "bpret"
[[]]
name = "bsdmgpath"
[[]]
name = "clamshell"
[[]]
name = "clump_size"
[[]]
name = "colors"
[[]]
name = "corefile_size_mb"
[[]]
name = "corpse_for_fatal_memkill"
[[]]
name = "cpu-factor"
[[]]
name = "cpumon_ustackshots_trigger_pct"
[[]]
name = "cpus"
[[]]
name = "cpus_defeatures"
[[]]
name = "cpus_per_pset"
[[]]
name = "cs_debug"
[[]]
name = "cs_enforcement_disable"
[[]]
name = "cs_enforcement_panic"
[[]]
name = "cs_library_val_enable"
[[]]
name = "cs_relax_platform_task_ports"
[[]]
name = "cwad"
[[]]
name = "cwae"
[[]]
name = "darkwake"
[[]]
name = "dart"
[[]]
name = "dataconstro"
[[]]
name = "dcc"
[[]]
name = "debug4k_filter"
[[]]
name = "delay_above_gb"
[[]]
name = "dextrelaunch"
[[]]
name = "diag"
[[]]
name = "diagnostic_api"
[[]]
name = "direct_handoff"
[[]]
name = "disable_NO_SMT_threads"
[[]]
name = "disable_exc_resource"
[[]]
name = "disable_persona_propagate_check"
[[]]
name = "dk"
[[]]
name = "drain_uart_sync"
[[]]
name = "dtrace_dof_mode"
[[]]
name = "dtrace_kernel_symbol_mode"
[[]]
name = "dyld_flags"
[[]]
name = "ebsz"
[[]]
name = "enable_copyout_shim"
[[]]
name = "enable_skstb"
[[]]
name = "enable_skstsct"
[[]]
name = "enforce_quiesce_safety"
[[]]
name = "entitled_max_task_pmem"
[[]]
name = "entropy-analysis-sample-count"
[[]]
name = "exc_resource_threads"
[[]]
name = "exc_via_corpse_forking"
[[]]
name = "execfailurecrashes"
[[]]
name = "fast_jetsam_enabled"
[[]]
name = "fastipi"
[[]]
name = "fill"
[[]]
name = "firehose_chunk_count"
[[]]
name = "firehose_io_pages"
[[]]
name = "fpsimd_fault_popc"
[[]]
name = "fq_codel_quantum"
[[]]
name = "gzalloc_fc_size"
[[]]
name = "gzalloc_max"
[[]]
name = "gzalloc_min"
[[]]
name = "gzalloc_size"
[[]]
name = "gzalloc_zscale"
[[]]
name = "gzname"
[[]]
name = "halt_restart_timeout"
[[]]
name = "haltmslog"
[[]]
name = "haltmspanic"
[[]]
name = "hcalls"
[[]]
name = "hfile"
[[]]
name = "himemory_mode"
[[]]
name = "hwm_user_cores"
[[]]
name = "ifa_debug"
[[]]
name = "ifclassq_target_qdelay"
[[]]
name = "ifclassq_update_interval"
[[]]
name = "ifnet_debug"
[[]]
name = "immediate_NMI"
[[]]
name = "imp_interactive_receiver"
[[]]
name = "ina6ddr_nhash"
[[]]
name = "inaddr_nhash"
[[]]
name = "initmcl"
[[]]
name = "insn_capcnt"
[[]]
name = "intcoproc_unrestricted"
[[]]
name = "intcpumax"
[[]]
name = "interrupt_accounting"
[[]]
name = "interrupt_latency_cap_us"
[[]]
name = "interrupt_masked_debug_timeout"
[[]]
name = "interrupt_watchdog"
[[]]
name = "io"
[[]]
name = "io_telemetry_limit"
[[]]
name = "io_throttle_period_tier1"
[[]]
name = "io_throttle_period_tier2"
[[]]
name = "io_throttle_period_tier3"
[[]]
name = "io_throttle_window_tier1"
[[]]
name = "io_throttle_window_tier2"
[[]]
name = "io_throttle_window_tier3"
[[]]
name = "iocthreads"
[[]]
name = "iokit_iomd_setownership_enabled"
[[]]
name = "iosched"
[[]]
name = "iotrace"
[[]]
name = "ip6_checkinterface"
[[]]
name = "ip_checkinterface"
[[]]
name = "ipc_control_port_options"
[[]]
name = "ipc_strict_reply"
[[]]
name = "jcon"
[[]]
name = "jetsam_aging_policy"
[[]]
name = "jetsam_idle_snapshot"
[[]]
name = "jtag"
[[]]
name = "kasan"
[[]]
name = "kasan.checks"
[[]]
name = "kasan.free_yield_ms"
[[]]
name = "kasan.leak_fatal_threshold"
[[]]
name = "kasan.leak_threshold"
[[]]
name = "kdp_crashdump_pkt_size"
[[]]
name = "kdp_ip_addr"
[[]]
name = "kdp_match_name"
[[]]
name = "keepsyms"
[[]]
name = "kern.jetsam_critical_threshold"
[[]]
name = "kern.jetsam_delta"
[[]]
name = "kern.jetsam_user_freezer_snapshot"
[[]]
name = "kern.thread_group_extra_bytes"
[[]]
name = "kern.thread_group_set_by_bankvoucher"
[[]]
name = "kernPOST"
[[]]
name = "kernPOST_config"
[[]]
name = "kernel_stack_pages"
[[]]
name = "kernelmanagerd"
[[]]
name = "kevent_debug"
[[]]
name = "kextlog"
[[]]
name = "kheap_temp_debug"
[[]]
name = "kmem"
[[]]
name = "lapic_dont_panic"
[[]]
name = "launchdsuffix"
[[]]
name = "lbr_support"
[[]]
name = "lcks"
[[]]
name = "legacy_footprint_entitlement_mode"
[[]]
name = "lo_txstart"
[[]]
name = "longterm"
[[]]
name = "lt_tbl_size"
[[]]
name = "malloc_no_cow"
[[]]
name = "max_cpumon_interval"
[[]]
name = "max_cpumon_percentage"
[[]]
name = "max_jetsam_threads"
[[]]
name = "max_task_pmem"
[[]]
name = "max_valid_dma_addr"
[[]]
name = "maxloreserve"
[[]]
name = "maxmem"
[[]]
name = "mbuf_debug"
[[]]
name = "mbuf_pool"
[[]]
name = "mcache_flags"
[[]]
description = "The \"memory device\""
name = "md"
[[]]
name = "memmap"
[[]]
name = "meter"
[[]]
name = "mleak_sample_factor"
[[]]
name = "mmio_uart"
[[]]
name = "mseg"
[[]]
name = "msgbuf"
[[]]
name = "mtxspin"
[[]]
name = "multiq_drain_band_limit"
[[]]
name = "multiq_drain_ceiling"
[[]]
name = "multiq_drain_depth_limit"
[[]]
name = "nbuf"
[[]]
name = "ncl"
[[]]
name = "nested_panic_max"
[[]]
name = "net_affinity"
[[]]
name = "net_async"
[[]]
name = "net_rtref"
[[]]
name = "net_rxpoll"
[[]]
name = "network-type"
[[]]
name = "no-dockfifo-uart"
[[]]
name = "no32exec"
[[]]
name = "no_interrupt_masked_debug"
[[]]
name = "noidle"
[[]]
name = "nointr_consio"
[[]]
name = "npvhash"
[[]]
name = "nvram-log"
[[]]
name = "nvram_paniclog"
[[]]
name = "panic_clmismatch"
[[]]
name = "panic_halt"
[[]]
name = "panic_io_port"
[[]]
name = "panic_on_cs_killed"
[[]]
name = "panic_on_trap_mask"
[[]]
name = "panic_on_trap_procname"
[[]]
name = "panic_on_unsigned_execute"
[[]]
name = "panic_restart_timeout"
[[]]
name = "panic_trace"
[[]]
name = "panicd_port"
[[]]
name = "pcie_mmio_uart"
[[]]
name = "pgtrace"
[[]]
name = "phyreadmaxus"
[[]]
name = "phys_carveout_mb"
[[]]
name = "phywritemaxus"
[[]]
name = "pmap_asid_plru"
[[]]
name = "pmap_asserts"
[[]]
name = "pmap_inp_max"
[[]]
name = "pmap_ledgers_panic"
[[]]
name = "pmap_ledgers_panic_leeway"
[[]]
name = "pmap_panic_dev_wimg_on_managed"
[[]]
name = "pmap_stats_assert"
[[]]
name = "pmap_trace"
[[]]
name = "pmsafe_debug"
[[]]
name = "pmtimeout"
[[]]
name = "policy_check"
[[]]
name = "poll"
[[]]
name = "preempt"
[[]]
name = "prioritize_launch"
[[]]
name = "pvpanic_io_port"
[[]]
name = "qos_override_mode"
[[]]
description = "The \"root device\""
name = "rd"
[[]]
name = "rlog"
[[]]
name = "rootdev"
[[]]
name = "rootpath"
[[]]
name = "rp"
[[]]
name = "rp0"
[[]]
name = "rp1"
[[]]
name = "rt_ini_count"
[[]]
name = "rte_debug"
[[]]
name = "sched_clutch_bucket_group_interactive_pri"
[[]]
name = "sched_debug"
[[]]
name = "sched_decay_penalty"
[[]]
name = "sched_decay_usage_age_factor"
[[]]
name = "sched_pri_decay_limit"
[[]]
name = "secluded_for_apps"
[[]]
name = "secluded_for_fbdp"
[[]]
name = "secluded_for_filecache"
[[]]
name = "secluded_for_iokit"
[[]]
name = "secluded_mem_mb"
[[]]
name = "secluded_shutoff_mb"
[[]]
name = "serial"
[[]]
name = "serialbaud"
[[]]
name = "serverperfmode"
[[]]
name = "setpowerstate_log"
[[]]
name = "setpowerstate_panic"
[[]]
name = "sigrestrict"
[[]]
name = "slto_us"
[[]]
name = "socket_debug"
[[]]
name = "stackshot_maxsz"
[[]]
name = "startup_debug"
[[]]
name = "statistics"
[[]]
name = "stop_clocks"
[[]]
name = "swd_panic"
[[]]
name = "swd_sleeptimeout"
[[]]
name = "swd_timeout"
[[]]
name = "swd_wakereason_panic"
[[]]
name = "swd_waketimeout"
[[]]
name = "task_exc_guard_default"
[[]]
name = "task_iomon_interval_secs"
[[]]
name = "task_iomon_limit_mb"
[[]]
name = "task_policy_suppression_flags"
[[]]
name = "task_wakeups_monitor_interval"
[[]]
name = "task_wakeups_monitor_rate"
[[]]
name = "task_wakeups_monitor_ustackshots_trigger_pct"
[[]]
name = "tcp_log"
[[]]
name = "telemetry_buffer_size"
[[]]
name = "telemetry_notification_leeway"
[[]]
name = "telemetry_sample_all_tasks"
[[]]
name = "telemetry_sample_rate"
[[]]
name = "text_corruption_panic"
[[]]
name = "tg_adaptive"
[[]]
name = "timebase_validation"
[[]]
name = "tlbto_us"
[[]]
name = "tlto_us"
[[]]
name = "trace"
[[]]
name = "tracephyreadus"
[[]]
name = "tracephywriteus"
[[]]
name = "ts_htable_buckets"
[[]]
name = "turnstile_max_hop"
[[]]
name = "uncore_pmi_mask"
[[]]
name = "unentitled_ios_sim_launch"
[[]]
name = "unique_persona"
[[]]
name = "unrestrict_coalition_syscalls"
[[]]
name = "unsafe"
[[]]
name = "up_style_idle_exit"
[[]]
name = "urgency_notification_abstime"
[[]]
name = "use_contiguous_hint"
[[]]
name = "validation_disables"
[[]]
name = "vm_check_map_sanity"
[[]]
name = "vm_compression_limit"
[[]]
name = "vm_compressor"
[[]]
name = "vm_compressor_codec"
[[]]
name = "vm_compressor_validation"
[[]]
name = "vm_footprint_suspend_allowed"
[[]]
name = "vm_map_debug_apple_protect"
[[]]
name = "vm_map_debug_fourk"
[[]]
name = "vm_map_executable_immutable"
[[]]
name = "vm_map_executable_immutable_verbose"
[[]]
name = "vm_max_num_swap_files"
[[]]
name = "vm_memory_malloc_no_cow_mask"
[[]]
name = "vm_object_tracking"
[[]]
name = "vm_page_bg_exclude_external"
[[]]
name = "vm_page_bg_mode"
[[]]
name = "vm_page_bg_target"
[[]]
name = "vm_protect_privileged_from_untrusted"
[[]]
name = "vm_restricted_to_single_processor"
[[]]
name = "vm_rtfault_records"
[[]]
name = "vm_shared_region_by_entitlement"
[[]]
name = "vm_shared_region_per_team_id"
[[]]
name = "vm_shared_region_reslide_aslr"
[[]]
name = "vm_shared_region_reslide_restrict"
[[]]
name = "vmcomp_ecluster"
[[]]
name = "vmcomp_threads"
[[]]
name = "vmpgo_pcluster"
[[]]
name = "vmpgoi_maxlaundry"
[[]]
name = "vnguard"
[[]]
name = "vps_dynamic_priority_enabled"
[[]]
name = "vti"
[[]]
name = "wdt"
[[]]
name = "wfe_events_sec"
[[]]
name = "wfe_mode"
[[]]
name = "wfi"
[[]]
name = "workaround_41447923"
[[]]
name = "wpkernel"
[[]]
name = "wql_tsize"
[[]]
name = "wqp_tsize"
[[]]
name = "wqsize"
[[]]
name = "wqt_min_free"
[[]]
name = "x2apic"
[[]]
name = "yield"
[[]]
name = "yield_delay_us"
[[]]
name = "zc_auto_enable_threshold"
[[]]
name = "zc_defrag_ratio"
[[]]
name = "zc_free_batch_size"
[[]]
name = "zc_grow_threshold"
[[]]
name = "zc_mag_size()"
[[]]
name = "zc_recirc_denom"
[[]]
name = "zclear_size"
[[]]
name = "zelems"
[[]]
name = "zfactor"
[[]]
name = "zleak-allocs"
[[]]
name = "zleak-traces"
[[]]
name = "zlog"
[[]]
name = "zone_foreign_pages"
[[]]
name = "zp-factor"
[[]]
name = "zp-scale"
[[]]
name = "zrecs"
[[]]
name = "zs"
[[]]
name = "zsize"