credit = ["https://nyansatan.github.io/lightning/"]
description = "Lightning Accessory IDs and protocols"
[accessory_id.dcsd]
description = "Apple diagnostic cable from the factory"
id = 200000000000
[accessory_id.dfu]
description = "Casues the Hydra/Tristar to assert the FORCE_DFU pin"
id = 524288
[accessory_id.haywire]
description = "Apple HDMI adapter"
id = "0BF000000000"
[accessory_id.headphone]
description = "Apple 3.5mm headphone adapter"
id = "04F100000000"
[accessory_id.kanzi_swd]
description = "Apple Kanzi cable in SWD single wire debug"
id = "A00C00000000"
[accessory_id.kanzi_swd_astris]
description = "Apple Kanzi cable in SWD single wire debug with Astris running"
id = "200E00000000"
[accessory_id.kong_swd]
description = "Apple Kong debug cable"
id = "A00000000000"
[accessory_id.kong_swd_astris]
description = "The ID presented by a Kong cable to enter serial wire debug with Astris running"
id = 200200000000
[accessory_id.reset]
description = "Causes the Hydra/Tristar to pull the device through reset"
id = "E00A00000000"
[accessory_id.uart]
description = "UART serial"
id = 200010000000