
[audioOS]
architectures = ["arm64","arm64e"]
[bridgeOS]
architectures = ["arm64"]
[iOS]
architectures = ["armv6","armv7","arm64","arm64e"]
[macOS]
archetectures = ["ppc","ppc64","x86","x86_64","x86_64h"]
[padOS]
architectures = ["armv7","arm64","arm64e"]
[tvOS]
architectures = ["x86","armv7","arm64","arm64e"]